baseURL = "https://jingyao-wei.github.io/"
languageCode = "en-us"
title = "Jingyao Wei"
disableKinds = ["taxonomy", "term", "rss"]

[params]
  author = "Jingyao Wei"
  tagline = "PhD Candidate in Economics, Norwegian School of Economics (NHH)"
  subtitle = ""
  description = "Jingyao Wei is a PhD candidate in Economics at NHH working on development, environmental, and health economics."
  email = "jingyao.wei@nhh.no"
  photo = "/images/photo.jpg"
  cv = "/files/cv.pdf"
  keywords = "Development Economics, Environmental Economics, Health Economics, Jingyao Wei, NHH"

  [params.mysite]
    credit = true
    discovery = true

[markup.goldmark.renderer]
  unsafe = true
